apiVersion: v2
name: kube-cleanup-operator
description: Kubernetes Operator to automatically delete completed Jobs and their Pods
type: application
version: 0.1.0
appVersion: v0.1.0
keywords:
  - kubernetes
  - operator
  - cleanup
sources:
  - https://github.com/jaredallard/kube-cleanup-operator.git
